#!/bin/bash
set -e

# This script will automatically install and configure Logstash and Kibana

# Grab the fullpath of our root directory
ROOT=$(cd `dirname ${BASH_SOURCE[0]}` && echo $PWD)

sudo add-apt-repository ppa:webupd8team/java -y
sudo apt-get update
sudo apt-get install -y --force-yes oracle-java7-installer rubygems ruby1.9.1-dev unzip nginx

# Install and configure elasticsearch
wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.5.deb -O /tmp/elasticsearch.deb
sudo dpkg -i /tmp/elasticsearch.deb
rm /tmp/elasticsearch.deb

# These configurations are for a large, 192GB Dell R720. You'll need to adjust
# them for use on any smaller systems.
cp $ROOT/etc/elasticsearch/elasticsearch.yml .
sudo cp $ROOT/default/elasticsearch /etc/default/elasticsearch
sudo /etc/init.d/elasticsearch start

# Logstash is just a jar and requires some additional configs
LOGHOME=/opt/logstash
sudo rm -rf LOGHOME
sudo mkdir $LOGHOME
pushd $LOGHOME
sudo wget http://logstash.objects.dreamhost.com/release/logstash-1.2.1-flatjar.jar -O logstash.jar
sudo cp $ROOT/conf/logstash-node.conf .
sudo cp $ROOT/init/logstash.conf /etc/init/
sudo mkdir /var/lib/logstash && sudo chown -R ubuntu:ubuntu /var/lib/logstash # Required working directory for logstash
sudo service logstash start
popd

# Install and configure the Kibana frontend
pushd /opt/
sudo rm -rf kibana
sudo wget sudo wget http://download.elasticsearch.org/kibana/kibana/kibana-latest.zip
sudo unzip kibana-latest.zip
sudo rm kibana-latest.zip
sudo mv kibana-latest kibana
popd

# Install and configure Nginx (serves Kibana)
pushd /etc/nginx/sites-available
sudo rm default
sudo cp $ROOT/etc/nginx/kibana .
sudo ln -s /etc/nginx/sites-available/kibana /etc/nginx/sites-enabled/kibana
sudo service nginx reload
popd


# Up the open FD limit for everyone
echo 'echo "soft nofile 1000000" >> /etc/security/limits.conf' | sudo bash
echo 'echo "hard nofile 1000000" >> /etc/security/limits.conf' | sudo bash

cat - <<FINISHED
Installation complete. 

Services running:

  Logstash UDP Server
  Elasticsearch
  Kibana

Kibana is listening on port 80.

FINISHED
