#!/bin/bash
set -e

# This script will automatically install and configure Logstash and Kibana

# Grab the fullpath of our root directory
ROOT=$(cd `dirname ${BASH_SOURCE[0]}` && echo $PWD)

sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install -y --force-yes oracle-java7-installer rubygems ruby1.9.1-dev

# Install and configure elasticsearch
wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.5.deb -O /tmp/elasticsearch.deb
sudo dpkg -i /tmp/elasticsearch.deb
rm /tmp/elasticsearch.deb

# These configurations are for a large, 192GB Dell R720. You'll need to adjust
# them for use on any smaller systems.
cp $ROOT/etc/elasticsearch/elasticsearch.yml .
cp $ROOT/default/elasticsearch /etc/default/elasticsearch
sudo /etc/init.d/elasticsearch start

# Logstash is just a jar and requires some additional configs
LOGHOME=/opt/logstash
sudo mkdir $LOGHOME && sudo chown -R ubuntu:ubuntu $LOGHOME && pushd $LOGHOME
wget http://logstash.objects.dreamhost.com/release/logstash-1.2.1-flatjar.jar -O logstash.jar
cp $ROOT/conf/logstash_server.conf .
sudo cp $ROOT/init/logstash.conf /etc/init/
sudo mkdir /var/lib/logstash && sudo chown -R ubuntu:ubuntu /var/lib/logstash # Required working directory for logstash
sudo service logstash start
popd

# Install and configure the Kibana frontend
pushd /opt/
git clone --branch=kibana-ruby https://github.com/rashidkpc/Kibana.git
pushd Kibana
sed -i 's#KibanaHost =.*#KibanaHost = "0.0.0.0"#' KibanaConfig.rb
sed -i 's#KibanaPort =.*#KibanaPort = 80#' KibanaConfig.rb
gem install bundler
bundle install
sudo cp $ROOT/init/kibana.conf /etc/init/kibana.conf
sudo service kibana start
popd

# Up the open FD limit for everyone
echo "soft nofile 1000000" >> /etc/security/limits.conf
echo "hard nofile 1000000" >> /etc/security/limits.conf

cat - <<FINISHED
Elasticsearch installation now complete. 

Services running:

  Logstash indexer
  Elasticsearch
  Redis
  Kibana

Kibana is listening on port 80.

FINISHED
